SHELL := /bin/bash
.DEFAULT_GOAL := help

# ─── CONFIG ───────────────────────────────────────────────────

BACKEND_DIR := backend
FRONTEND_DIR := frontend

# ─── HELP ─────────────────────────────────────────────────────

# Self-updating help: sections come from `# ─── NAME ───` separators and
# entries from `target: ## description` lines. Add a target below and it
# shows up here automatically. Sections CONFIG/HELP are skipped.

.PHONY: help
help: ## Show available targets
	@if [ -t 1 ] && [ -z "$$NO_COLOR" ]; then \
		HDR=$$'\033[1;32m'; CMD=$$'\033[1;34m'; DIM=$$'\033[2m'; END=$$'\033[0m'; \
	else \
		HDR=""; CMD=""; DIM=""; END=""; \
	fi; \
	echo "ShahrAra — Municipal Engagement System"; \
	echo ""; \
	echo "$${DIM}Usage: make <target>$${END}"; \
	echo ""; \
	awk -v hdr="$$HDR" -v cmd="$$CMD" -v end="$$END" ' \
		/^# ─── .* ───/ { \
			s = $$0; sub(/^# ─── /, "", s); sub(/ ───.*$$/, "", s); \
			if (s != "CONFIG" && s != "HELP") { \
				if (body) printf "\n"; \
				printf "%s%s:%s\n", hdr, s, end; \
				pending = 1; body = 0; \
			} \
			next; \
		} \
		/^[a-zA-Z][a-zA-Z0-9_-]*:.*## / { \
			if (!pending) next; \
			name = $$1; sub(/:.*$$/, "", name); \
			if (name == "help") next; \
			desc = $$0; sub(/^[^#]*## /, "", desc); \
			printf "  %s%-18s%s %s\n", cmd, name, end, desc; \
			body = 1; \
		} \
	' $(firstword $(MAKEFILE_LIST)); \
	echo ""; \
	echo "$${DIM}Use \`make help\` to show this message$${END}"

# ─── INSTALL ──────────────────────────────────────────────────

.PHONY: install
install: install-backend install-frontend ## Install all dependencies

.PHONY: install-backend
install-backend: ## Install backend dependencies (uv)
	cd $(BACKEND_DIR) && uv sync

.PHONY: install-frontend
install-frontend: ## Install frontend dependencies (pnpm)
	cd $(FRONTEND_DIR) && pnpm install

# ─── RUN ──────────────────────────────────────────────────────

.PHONY: dev-backend
dev-backend: ## Run backend dev server
	cd $(BACKEND_DIR) && uv run uvicorn main:app --host 0.0.0.0 --port 8000 --reload

.PHONY: dev-frontend
dev-frontend: ## Run frontend dev server
	cd $(FRONTEND_DIR) && pnpm dev

# ─── DATABASE ─────────────────────────────────────────────────

.PHONY: db-up
db-up: ## Start database container
	docker compose up -d db

.PHONY: db-down
db-down: ## Stop database container
	docker compose down

.PHONY: db-logs
db-logs: ## Follow database container logs
	docker compose logs -f db

.PHONY: db-migrate
db-migrate: ## Apply pending migrations (alembic upgrade head)
	cd $(BACKEND_DIR) && uv run alembic upgrade head

.PHONY: db-revision
db-revision: ## Create new autogenerated migration (m="message")
	cd $(BACKEND_DIR) && uv run alembic revision --autogenerate -m "$(m)"

.PHONY: seed
seed: ## Seed database with sample data
	cd $(BACKEND_DIR) && uv run python -m scripts.seed

# ─── TEST ─────────────────────────────────────────────────────

.PHONY: test
test: ## Run backend tests
	cd $(BACKEND_DIR) && uv run pytest

# ─── LINT / FORMAT ────────────────────────────────────────────

.PHONY: lint
lint: lint-backend lint-frontend ## Lint backend and frontend

.PHONY: lint-backend
lint-backend: ## Lint backend (ruff)
	cd $(BACKEND_DIR) && uv run ruff check .

.PHONY: lint-frontend
lint-frontend: ## Lint frontend (eslint)
	cd $(FRONTEND_DIR) && pnpm lint

.PHONY: format
format: format-backend format-frontend ## Format backend and frontend

.PHONY: format-backend
format-backend: ## Format backend (ruff)
	cd $(BACKEND_DIR) && uv run ruff format .

.PHONY: format-frontend
format-frontend: ## Format frontend (prettier)
	cd $(FRONTEND_DIR) && pnpm exec prettier --write .

# ─── HOOKS ────────────────────────────────────────────────────

.PHONY: hooks
hooks: ## Install lefthook git hooks
	lefthook install
